config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root :to => "welcome#index"
  resources :registrar
  resources :ingresar

end

app/models/user.rb
class User < ActiveRecord::Base
	validates_length_of :nombre, :maximum => 30
	validates_length_of :apellido, :maximum => 30
	validates_length_of :fono, :maximum => 30
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
				format: { with:VALID_EMAIL_REGEX}, 
				uniqueness: { case_sensitive: false }
	validates_length_of :direccion, :maximum => 30
	has_secure_password
	validates_confirmation_of :password
	validates_presence_of :password_digest, :message => "ingrese password"
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingresar_controller.rb
class IngresarController < ApplicationController
	def new
		@usuario = User.new()
	end

	def create
		if @usuario = login(params[:nombre],params[:password_diest])
		refirect_back_or_to(welcome_path, message: "login exitoso")
		else
			sadf
			flash.now[:alert] = "Algo salio mal"
			render action: :new
		end
	end

	def destroy
		logout
		redirect_to(:usuario, message: "Salio")
	end
end

app/controllers/registrar_controller.rb
class RegistrarController < ApplicationController

	def new
		@usuario = User.new()

	end

	def create
		@usuario = User.new(user_params)
		if @usuario.save
			flash[:success]="Bienvenido"
			redirect_to @usuario
		else
			render action: 'new'
		end
	end

	private
	def user_params
		params.require(:usuario).permit(:nombre,:apellido,:fono,:email,:direccion,:password,:password_confirmation)
		
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingresar_helper.rb
module IngresarHelper
end

app/helpers/registrar_helper.rb
module RegistrarHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ingresar/new.html.erb
<h1>Ingrese</h1>
<%= form_for :usuario, url: ingresar_index_path do |f| %>
<p>
	<%= f.label :Nombre %><br>
	<%= f.text_field :nombre %>
</p>

<p>
	<%= f.label :Password %><br>
	<%= f.text_field :password_digest %>
</p>
<p>
	<%= f.submit 'Ingresar'%>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/registrar/index.html.erb
<h1>Nuevo Usuario</h1>
	<%= form_for :post do |f| %>		
	<p>
		<%= f.label :Nombre %><br>
		<%= f.text_field :nombre %>
	</p>
	<p>
		<%= f.label :Apellido %><br>
		<%= f.text_field :apellido %>
	</p>
	<p>
		<%= f.label :Telefono %><br>
		<%= f.text_field :telefono %>
	</p>
	<p>
		<%= f.label :Email %><br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :Direccion %><br>
		<%= f.text_field :direccion %>
	</p>
	<p>
		<%= f.label :Password %><br>
		<%= f.text_field :password %>
	</p>
	<p>
		<%= f.label :Confirmar_password%><br>
		<%= f.text_field :confirmar_password %>
	</p>
	<p>
    <%= f.submit 'crear'%>
  	</p>
	<% end %>

app/views/registrar/new.html.erb
<h1>Nuevo Usuario</h1>


	<%= form_for :usuario, url: registrar_index_path do |f| %>

	<p>
		<%= f.label :Nombre %><br>
		<%= f.text_field :nombre %>
	</p>
	<p>
		<%= f.label :Apellido %><br>
		<%= f.text_field :apellido %>
	</p>
	<p>
		<%= f.label :fono %><br>
		<%= f.text_field :fono %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :Direccion %><br>
		<%= f.text_field :direccion %>
	</p>
	<p>
		<%= f.label :Password %><br>
		<%= f.text_field :password %>
	</p>
	<p>
		<%= f.label :Confirmar_password%><br>
		<%= f.text_field :password_confirmation %>
	</p>
	<p>
    <%= f.submit 'crear'%>
  	</p>
	<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Gamestore</h1>

<td><%= link_to "registrar", new_registrar_path %></td>
<td><%= link_to "Ingresar", new_ingresar_path %></td>

<p>Find me in app/views/welcome/index.html.erb</p>